### ISSUE TITLE
关于字体调整的问题

### ISSUE THREAD

**Issue by MachaCroissant** [HanryYu/typora-blubook-theme#23]
主要以下三点：

- 在代码字体有点太小了，内联代码最好比中文字体小一些，行间代码最好比现在的字体大一些。行间代码的提示语言那个背景色有点太深了，基本上看不见里面是啥字。

- 在左侧列表视图中，就是有文件描述和文件名的那个列表，文件名那个块的盒子的内容高度设置得有点小，以至于像y/p这种字母下半段就像被截断了一样。

- 另外，我用hexo生成的md文件在最上部的文章字段配置的模块字体特别特别小，不知道是不是该主题根字体设置得太小的问题。

最后，这个主题很漂亮～谢谢分享！

**Comment by FishionYu** [comment]
我自己不太喜欢代码字体太大的样式，所以现在定的有点小，下一个版本我会调整一个合适的出来。因为之前一直在调暗色版本，工作也有点忙，近期更新有点慢，这些问题（包括暗色版本）我会在下一个更新优化掉
