### ISSUE TITLE
Font-size

### ISSUE THREAD

**Issue by KoduckShih** [HanryYu/typora-blubook-theme#47]
**The font-size of p{} and html, body{} is set to pixel units.
it is recommended to use rem units, it will allow convenient font-size modification in appearance setting.**

**Comment by Higurashi-kagome** [comment]
Thanks for your feedback! That's true, so we fixed this in the [latest version](https://github.com/FishionYu/typora-blubook-theme/blob/master/blubook.css#L299)([L299](https://github.com/FishionYu/typora-blubook-theme/blob/4325ad05d26356169b9c88941c83a2b3b5dd9ccc/blubook.css#L299)). Try to use it and contact if get any issue👋.
