### ISSUE TITLE
CodeMirror size

### ISSUE THREAD

**Issue by FatWang1** [HanryYu/typora-blubook-theme#60]
hello，i have tried to set CodeMirror`s size failed by google, due to be unfamiliar with front-end.
could you please tell me how can i set it?
besides, chinese is friendly to me.

**Comment by HanryYu** [comment]
Hi, The width of the code block is aligned with the editing area. You can change the blubook.css at `#write` `max-width: 700px`. You can change the `max-width` value as you like.
![image](https://user-images.githubusercontent.com/20253239/131447371-d675d3ca-2fee-4ed8-a890-5c88c512278c.png)
![image](https://user-images.githubusercontent.com/20253239/131447736-effd178f-af15-4bd2-b89c-e3944c3f74e0.png)

**Comment by FatWang1** [comment]
thank you so much
