### ISSUE TITLE
Missing style in Quick Open

### ISSUE THREAD

**Issue by AlexPasternak** [HanryYu/typora-blubook-theme#61]
In the Quick Open dialog, one font must be unstyled, so which makes file names not currently highlighted unreadable.

In this sample, I cannot read what the first filename is in the selection. Can you please fix this? Great theme otherwise!

![2021-12-07 8 37 56 AM](https://user-images.githubusercontent.com/1819485/145039250-4e0c85e9-48f2-4d03-ac55-609799e535a4.jpg)

**Comment by HanryYu** [comment]
Can you try the last changed file? I tested the issue and it's fixed.

You can download it [here](https://github.com/HanryYu/typora-blubook-theme/raw/master/blubook.css).

![image](https://user-images.githubusercontent.com/20253239/145127930-1bef2979-0b83-491f-bd5f-27d8ed5128e4.png)

**Comment by AlexPasternak** [comment]
Much better, issue is resolved. Thanks for the fast turnaround!
