### ISSUE TITLE
C/C++代码块里面的!=符号显示有点问题

### ISSUE THREAD

**Issue by blueyolo** [HanryYu/typora-blubook-theme#64]
大神您好。C/C++代码块里面的``!=``符号显示有些问题。python显示的是正常的
<img width="665" alt="WechatIMG63" src="https://user-images.githubusercontent.com/80201320/174806089-3676e6b9-c296-4b7b-845c-6948c2c0a4e8.png">

**Comment by HanryYu** [comment]
这个是 cascadia code 字体的连字效果，算是一个 feature

**Comment by EveningMeeting** [comment]
如果想要怎么取消连字的话，应该怎么改

**Comment by HanryYu** [comment]
打开 css 文件，搜索 `#write .cm-s-inner .CodeMirror-gutters`，然后在最后增加`font-variant-ligatures: none;`即可
