### ISSUE TITLE
在使用公式块的情况下，预览字体为黑色，很难看清

### ISSUE THREAD

**Issue by Chauncywu1999** [HanryYu/typora-blubook-theme#66]
<img width="1041" alt="截屏2023-03-18 20 28 04" src="https://user-images.githubusercontent.com/44538024/226106067-9624dddb-2e8e-45ad-a674-db3ff643fb60.png">

**Comment by HanryYu** [comment]
最新的 release 已修复。
The latest release has been fixed.

**Comment by Chauncywu1999** [comment]
👍
